[project]
name = "mlops-mlflow"
version = "0.1.0"
description = "iris flower prediction "
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mlflow>=3.4.0",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
]
